"""Generate an ICD-10 coverage review sheet for every condition bucket.

No LLM. Reads the conditions map and cross-checks each bucket's assigned ICD-10-CM
code against the licensed category table (data/icd10cm.csv, 3-char categories +
official titles). For any bucket with NO code, runs a token-overlap search over the
table titles so a human can judge which category fits. Deterministic script +
human review -- codes are never assigned by a model.

Handles BOTH schemas so it is useful before and after migration:
  old  {bucket: [synonyms...]}                    -> every bucket is "null-code"
  new  {bucket: {icd10, icd10_title, aliases}}     -> verify code vs the table

Run:  ./venv/bin/python -m tools.conditions_coverage [path/to/conditions.json]
Out:  docs/conditions-coverage-review.md
"""

from __future__ import annotations

import csv
import json
import re
import sys

CSV = "data/icd10cm.csv"
OUT = "docs/conditions-coverage-review.md"
DEFAULT_SRC = "data/conditions.json"

_STOP = {
    "of",
    "in",
    "by",
    "the",
    "and",
    "a",
    "an",
    "other",
    "unspecified",
    "not",
    "elsewhere",
    "classified",
    "disease",
    "disorder",
    "acute",
    "chronic",
}


def load_categories() -> dict[str, str]:
    """LOINC-style: return {3-char category code -> official title}."""
    out: dict[str, str] = {}
    csv.field_size_limit(10**7)
    with open(CSV, newline="", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) < 2:
                continue
            code, title = row[0].strip(), row[1].strip()
            if len(code) == 3:  # a category, not a leaf code
                out[code] = title
    return out


def toks(s: str) -> set[str]:
    return {t for t in re.split(r"[^a-z0-9]+", (s or "").lower()) if t and t not in _STOP}


def candidates(terms: list[str], titles: dict[str, str], limit: int = 5) -> list[tuple[str, str]]:
    """Token-overlap search over category TITLES for a code-less bucket.

    Clinical abbreviations (HTN, CKD) will not token-match a formal title -- this
    is a curation aid for the spelled-out terms, not an oracle; the human fills
    the gaps, exactly as tools/loinc_coverage.py does for null-code analytes.
    """
    want = set().union(*(toks(t) for t in terms)) if terms else set()
    if not want:
        return []
    scored = []
    for code, title in titles.items():
        overlap = want & toks(title)
        if overlap:
            scored.append((len(overlap), code, title))
    scored.sort(key=lambda x: (-x[0], x[1]))
    return [(c, t) for _, c, t in scored[:limit]]


def esc(s: str) -> str:
    return (s or "").replace("|", "\\|")


def normalise(raw: dict) -> dict[str, dict]:
    """Coerce either schema to {bucket: {icd10:[...], icd10_title, aliases:[...]}}."""
    out: dict[str, dict] = {}
    for key, val in raw.items():
        if key.startswith("_"):
            continue
        if isinstance(val, dict):  # new schema
            out[key] = {
                "icd10": list(val.get("icd10") or []),
                "icd10_title": val.get("icd10_title") or "",
                "aliases": list(val.get("aliases") or []),
            }
        else:  # old schema: list of synonyms, no code
            out[key] = {"icd10": [], "icd10_title": "", "aliases": list(val or [])}
    return out


def main() -> None:
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    with open(src, encoding="utf-8") as f:
        buckets = normalise(json.load(f))
    titles = load_categories()

    coded = {k: v for k, v in buckets.items() if v["icd10"]}
    null = {k: v for k, v in buckets.items() if not v["icd10"]}

    lines: list[str] = []
    lines.append("# ICD-10 conditions coverage review\n")
    lines.append(f"Generated by `tools/conditions_coverage.py` from `{src}` vs `{CSV}`. No LLM.\n")
    lines.append(f"- Buckets total: **{len(buckets)}**")
    lines.append(f"- With an ICD-10 code: **{len(coded)}**")
    lines.append(f"- With NO code: **{len(null)}**\n")

    # --- Coded: verify our code against the licensed category table ----------
    lines.append("## Coded buckets (our code vs ICD-10-CM category table)\n")
    lines.append(
        "`✓` = our stored `icd10_title` matches the table's official title. "
        "`⚠` = code exists but our title differs (check). "
        "`✗` = code is not a 3-char category in the table.\n"
    )
    lines.append(
        "| ok | bucket (runtime key) | code | our title | table official title | aliases |"
    )
    lines.append("|---|---|---|---|---|---|")
    for key in coded:
        v = coded[key]
        for code in v["icd10"]:
            table_title = titles.get(code)
            ours = v["icd10_title"]
            if table_title is None:
                mark, tt = "✗", "— not a 3-char category —"
            else:
                tt = table_title
                mark = "✓" if ours.strip().lower() == tt.strip().lower() else "⚠"
            lines.append(
                f"| {mark} | {esc(key)} | {code} | {esc(ours)} | {esc(tt)} | "
                f"{esc(', '.join(v['aliases']))} |"
            )

    # --- Null: which category plausibly fits? --------------------------------
    lines.append("\n## Code-less buckets — candidate ICD-10 categories\n")
    lines.append(
        "Token-overlap over category titles (abbreviations won't match — a curation "
        "aid, not an oracle). Empty ⇒ decide by hand or leave the bucket code-less.\n"
    )
    if not null:
        lines.append("_None — every bucket has a code._\n")
    for key, v in null.items():
        lines.append(f"### {esc(key)}")
        lines.append(f"- aliases: {esc(', '.join(v['aliases'])) or '_none_'}")
        cands = candidates([key, *v["aliases"]], titles)
        if not cands:
            lines.append("- _no candidate found_\n")
            continue
        for code, title in cands:
            lines.append(f"  - `{code}` — {esc(title)}")
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(coded)} coded, {len(null)} null", file=sys.stderr)


if __name__ == "__main__":
    main()
