"""Generate a LOINC-coverage review sheet for every analyte in the codebook.

No LLM. Reads the consolidated codebook (data/analytes.json, via load_codebook)
and cross-checks each mapping against the licensed LOINC table (data/loinc.csv).
For any analyte with NO code, greps the table for candidate codes so a human can
judge whether a real LOINC exists. (Post-consolidation every analyte is coded, so
the null section should be empty; the tool stays useful when new analytes land.)

Run:  ./venv/bin/python -m tools.loinc_coverage   (or point PYTHONPATH at repo)
Out:  docs/loinc-coverage-review.md
"""

from __future__ import annotations

import csv
import re
import sys

from src.normalize import load_codebook

CSV = "data/loinc.csv"
OUT = "docs/loinc-coverage-review.md"

# CSV is ~109k rows; only these columns are needed.
KEEP = (
    "LOINC_NUM",
    "COMPONENT",
    "SYSTEM",
    "SCALE_TYP",
    "METHOD_TYP",
    "CLASS",
    "STATUS",
    "LONG_COMMON_NAME",
    "EXAMPLE_UCUM_UNITS",
    "COMMON_TEST_RANK",
)

_STOP = {
    "of",
    "in",
    "by",
    "the",
    "and",
    "a",
    "an",
    "count",
    "level",
    "serum",
    "blood",
    "test",
    "total",
}


def load_csv() -> tuple[dict, list]:
    """Return (by_code, rows) where by_code maps LOINC_NUM -> trimmed row dict."""
    by_code, rows = {}, []
    csv.field_size_limit(10**7)
    with open(CSV, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            slim = {k: r.get(k, "") for k in KEEP}
            by_code[slim["LOINC_NUM"]] = slim
            rows.append(slim)
    return by_code, rows


def toks(s: str) -> set[str]:
    return {t for t in re.split(r"[^a-z0-9]+", (s or "").lower()) if t and t not in _STOP}


def candidates(name: str, rows: list, limit: int = 4) -> list:
    """Cheap token-overlap search over COMPONENT for a null-code analyte.
    Prefers ACTIVE rows and common ones (low COMMON_TEST_RANK != 0)."""
    want = toks(name)
    if not want:
        return []
    scored = []
    for r in rows:
        if r["STATUS"] != "ACTIVE":
            continue
        have = toks(r["COMPONENT"])
        overlap = want & have
        if len(overlap) < max(1, len(want) - 1):  # nearly all name tokens present
            continue
        rank = int(r["COMMON_TEST_RANK"] or 0)
        # score: token overlap, then commonness (rank>0 ranked ahead of 0)
        scored.append(((len(overlap), rank > 0, -(rank or 10**9)), r))
    scored.sort(key=lambda x: x[0], reverse=True)
    seen, out = set(), []
    for _, r in scored:
        if r["LOINC_NUM"] in seen:
            continue
        seen.add(r["LOINC_NUM"])
        out.append(r)
        if len(out) >= limit:
            break
    return out


def esc(s: str) -> str:
    return (s or "").replace("|", "\\|")


def main() -> None:
    codebook = load_codebook()
    by_code, rows = load_csv()

    coded, null = [], []
    for name, e in sorted(codebook.items(), key=lambda kv: (kv[1].get("segment") or "~", kv[0])):
        (coded if e.get("loinc") else null).append((name, e))

    lines = []
    lines.append("# LOINC coverage review\n")
    lines.append(f"Generated by `tools/loinc_coverage.py` from `{CSV}`. No LLM.\n")
    lines.append(f"- Analytes total: **{len(codebook)}**")
    lines.append(f"- With a LOINC code: **{len(coded)}**")
    lines.append(f"- With NO code (the `local:` question): **{len(null)}**\n")

    # --- Coded: verify our code against the licensed table -------------------
    lines.append("## Coded analytes (our code vs licensed LOINC table)\n")
    lines.append(
        "`✓` = our stored name matches the table's LONG_COMMON_NAME. "
        "`⚠` = code exists but our name differs (check). "
        "`✗` = code not found in table.\n"
    )
    lines.append(
        "| ok | segment | analyte | code | our name | table LONG_COMMON_NAME "
        "| table UCUM | our ucum | status |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for name, e in coded:
        code = e["loinc"]
        row = by_code.get(code)
        ours = e.get("loinc_name") or ""
        if not row:
            mark, tname, tucum, tstat = "✗", "— not in table —", "", ""
        else:
            tname = row["LONG_COMMON_NAME"]
            tucum = row["EXAMPLE_UCUM_UNITS"]
            tstat = row["STATUS"]
            mark = "✓" if ours.strip().lower() == tname.strip().lower() else "⚠"
        lines.append(
            f"| {mark} | {esc(e.get('segment'))} | {esc(name)} | {code} | "
            f"{esc(ours)} | {esc(tname)} | {esc(tucum)} | {esc(e.get('ucum'))} | {tstat} |"
        )

    # --- Null: does a real code plausibly exist? -----------------------------
    lines.append("\n## Null-code analytes — candidate LOINCs from the table\n")
    lines.append(
        "Token-overlap search over COMPONENT (ACTIVE rows). "
        "Empty candidate list ⇒ likely genuinely code-less (needs `local:` or stays null).\n"
    )
    for name, e in null:
        lines.append(f"### {esc(name)}  ·  _{esc(e.get('segment') or 'blood')}_")
        cands = candidates(name, rows)
        if not cands:
            lines.append("- _no candidate found_\n")
            continue
        lines.append("| code | component | system | scale | long common name | ucum |")
        lines.append("|---|---|---|---|---|---|")
        for r in cands:
            lines.append(
                f"| {r['LOINC_NUM']} | {esc(r['COMPONENT'])} | {esc(r['SYSTEM'])} | "
                f"{esc(r['SCALE_TYP'])} | {esc(r['LONG_COMMON_NAME'])} | "
                f"{esc(r['EXAMPLE_UCUM_UNITS'])} |"
            )
        lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: {len(coded)} coded, {len(null)} null", file=sys.stderr)


if __name__ == "__main__":
    main()
